# Generated by Django 2.2 on 2021-11-05 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user-photo/', verbose_name='Фото пользователя'),
        ),
        migrations.CreateModel(
            name='Estimation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimation', models.IntegerField(choices=[(-1, 'Дизлайк'), (1, 'Лайк')], default=-1, verbose_name='Оценка')),
                ('who_rated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_rated_user', to=settings.AUTH_USER_MODEL, verbose_name='Кто оценил')),
                ('who_was_rated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_was_rated_user', to=settings.AUTH_USER_MODEL, verbose_name='Кого оценили')),
            ],
            options={
                'verbose_name': 'оценка',
                'verbose_name_plural': 'Оценки',
                'unique_together': {('who_rated', 'who_was_rated')},
            },
        ),
    ]
