# Generated by Django 2.2 on 2021-11-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211105_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.FloatField(default=0, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.FloatField(default=0, verbose_name='Долгота'),
        ),
    ]
